---
  - name: base-tools
    hosts: linux
    become: true
    become_method: sudo
    become_user: "{{account}}"

    tasks:
      - name: Intall base tools
        apt:
            pkg:
                - curl
                - nmap
                - build-essential
                - xfce4-sensors-plugin
                - xfce4-terminal
                - vlc
                - gparted
                - maven
                - kolourpaint
                - tree
                - openssl
            state: present
