---
  - name: base-tools
    hosts: linux
    become: yes

    tasks:
        - name: update packages
          apt: 
            update_cache: yes

        - name: Intall base tools
          apt:
              name:
                  - curl
                  - nmap
                  - build-essential
                  - xfce4-sensors-plugin
                  - xfce4-terminal
                  - vlc
                  - gparted
                  - maven
                  - kolourpaint
                  - tree
                  - openssl
                  - rar
                  - unrar
                  - zip
                  - unzip
                  - javacc
              state: present
