---
- name: dev-install
  hosts: linux
  become: true
  become_method: sudo
  become_user: "{{ account }}"

  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Config email for git
      git_config:
          name: user.email
          scope: global
          value: "{{ gitemail }}"

    - name: Config user for git
      git_config:
          name: user.name
          scope: global
          value: "{{ gituser }}"

