---
- name: vim-install
  hosts: linux
  become: true
  become_method: sudo
  become_user: "{{account}}"

  vars:
    account: 'server'
    home: "{{out.stdout}}"

  tasks:
    - name: Install Vim
      apt:
        name: vim
        state: present

    - name: Saving home directory
      shell: "echo $HOME"
      register: out

    - name: Cleaning old files
      file:
        path: 
          - "{{home}}/.vim/"
          - "{{home}}/.vimrc"
        state: absent

    - name: Creatig directory for save vim-plug
      file:
        path: "{{home}}/.vim/autoload/"
        state: directory

    - name: Get vim-plug from repo and copy to directory
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{home}}/.vim/autoload/"

    - name: Copy vimrc configuration to home directory of the user
      copy:
        src: "./dotfiles/.vimrc"
        dest: "{{home}}"
